/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.3.0-Docker-3.3.0 (4.3)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the InterfaceTemplateType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InterfaceTemplateType{}

// InterfaceTemplateType struct for InterfaceTemplateType
type InterfaceTemplateType struct {
	Value *InterfaceTypeValue `json:"value,omitempty"`
	Label *InterfaceTemplateTypeLabel `json:"label,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InterfaceTemplateType InterfaceTemplateType

// NewInterfaceTemplateType instantiates a new InterfaceTemplateType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInterfaceTemplateType() *InterfaceTemplateType {
	this := InterfaceTemplateType{}
	return &this
}

// NewInterfaceTemplateTypeWithDefaults instantiates a new InterfaceTemplateType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInterfaceTemplateTypeWithDefaults() *InterfaceTemplateType {
	this := InterfaceTemplateType{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *InterfaceTemplateType) GetValue() InterfaceTypeValue {
	if o == nil || IsNil(o.Value) {
		var ret InterfaceTypeValue
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceTemplateType) GetValueOk() (*InterfaceTypeValue, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *InterfaceTemplateType) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given InterfaceTypeValue and assigns it to the Value field.
func (o *InterfaceTemplateType) SetValue(v InterfaceTypeValue) {
	o.Value = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *InterfaceTemplateType) GetLabel() InterfaceTemplateTypeLabel {
	if o == nil || IsNil(o.Label) {
		var ret InterfaceTemplateTypeLabel
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InterfaceTemplateType) GetLabelOk() (*InterfaceTemplateTypeLabel, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *InterfaceTemplateType) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given InterfaceTemplateTypeLabel and assigns it to the Label field.
func (o *InterfaceTemplateType) SetLabel(v InterfaceTemplateTypeLabel) {
	o.Label = &v
}

func (o InterfaceTemplateType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InterfaceTemplateType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InterfaceTemplateType) UnmarshalJSON(data []byte) (err error) {
	varInterfaceTemplateType := _InterfaceTemplateType{}

	err = json.Unmarshal(data, &varInterfaceTemplateType)

	if err != nil {
		return err
	}

	*o = InterfaceTemplateType(varInterfaceTemplateType)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		delete(additionalProperties, "label")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInterfaceTemplateType struct {
	value *InterfaceTemplateType
	isSet bool
}

func (v NullableInterfaceTemplateType) Get() *InterfaceTemplateType {
	return v.value
}

func (v *NullableInterfaceTemplateType) Set(val *InterfaceTemplateType) {
	v.value = val
	v.isSet = true
}

func (v NullableInterfaceTemplateType) IsSet() bool {
	return v.isSet
}

func (v *NullableInterfaceTemplateType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInterfaceTemplateType(val *InterfaceTemplateType) *NullableInterfaceTemplateType {
	return &NullableInterfaceTemplateType{value: val, isSet: true}
}

func (v NullableInterfaceTemplateType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInterfaceTemplateType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


